### ISSUE TITLE
add nice GIF figure in the README

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ms-challenge-2021#57]
It would be important to have a nice landing page on this repository. I'm thinking of this subject as a starting point: https://github.com/ivadomed/ms-challenge-2021/pull/11#issuecomment-850515722

The idea would be to create two GIFs:
- one GIF showing the segmentation of all lesion. Animation would show: [anat image, overlay of brain mask, overlay of lesions]
- one GIF showing the segmentation of NEW lesions. Animation would show: [anat image time point 1, anat image time point 2, overlay of NEW lesion (circled to show it well)]

**Comment by uzaymacar** [comment]
Just updated the README!

**Comment by jcohenadad** [comment]
nice! few suggestions
- in the futur, pls work with PR for updating the repository, so you can get feedback from the team before updating the main branch
- i suggest showing a GIF at section https://github.com/ivadomed/ms-challenge-2021#preprocessing, e.g. you could take one subject from your big GIF and show it directly in the README.
- add a section "how to use" or "getting started", it helps for reproducibility/reusability
